# Site settings
title: Siddharth Patel
description: Welcome to my personal website!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "http://www.individual.utoronto.ca/sidpatel/"

# User settings
username: Siddharth Patel
user_description: Hello there! I'm a 3rd year University of Toronto student pursuing a HBSc. in Computer Science - Specialist Entrepreneurship stream. Currently I'm working as a Full Stack Developer at UofT. When I'm not busy writing complex algorithms for my assignments you can find me tinkering with my car or getting those six packs at the gym. My great "wow" moment was getting a TA offer while I was in my second year! It was an amazing opportunity to teach a Comp Sci course (CSCA08) so early on in my career. Want to work together? I’d love to hear from you.
user_title: Software Developer
email: sid.patel@mail.utoronto.ca
github_username: Patel-Sid


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
