# Site settings
title: Siddharth Patel
description: Welcome to my personal website!
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "http://www.individual.utoronto.ca/sidpatel/"

# User settings
username: Siddharth Patel
user_description: It feels just like yesterday when I was so excited to submit my print("Hello World") program as my first exercise in my CS class. Now, here I'm graduating (doesn't feel like it during this global pandemic) from Univeristy of Toronto with Honours BSc. (specialist in Computer Science)! I moved thousands of miles away from family to study CS but my passion didn't stop there. I quickly became a TA for a python class in second year and moved onto working for one of the largest banks in Canada for my co-op terms. After my 1 year experience at RBC (details below!), I decided to do a work-study position at U of T as a full-stack developer where I got my hands dirty with graphQL, TypeScript and VueJS. Now, being indepedent is tough especially if you are the chef (have to feed myself), mechanic (working on my car), maid (who loves chores?) and student all at the same time! So I decided visit family for my final semester and had to reject a 4th year TA offer! (hardest rejection of my life) But soon after TD scooped me up and I have been working as a SAS Analyst ever since (almost a year)! If want to work together, don't hesitate to get in touch with me, I would love to hear back from you!
user_title: Software Developer
email: sid.patel@mail.utoronto.ca
github_username: Patel-Sid


# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

theme: jekyll-theme-cayman
